name: Deploy to VPS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Composer dependencies
        run: composer install --optimize-autoloader --no-dev

      - name: Install npm dependencies
        run: pnpm install

      - name: Build assets
        run: pnpm run build

      - name: Generate key
        run: php artisan key:generate

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ${{ secrets.VPS_PATH }}
            git pull origin main
            composer install --optimize-autoloader --no-dev
            pnpm install
            pnpm run build
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo chown -R www-data:www-data ${{ secrets.VPS_PATH }}
            sudo chmod -R 755 ${{ secrets.VPS_PATH }}
            sudo chmod -R 775 ${{ secrets.VPS_PATH }}/storage
            sudo chmod -R 775 ${{ secrets.VPS_PATH }}/bootstrap/cache
