name: Deploy to VPS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" # ← Corrigido para 8.3
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, json, pdo, zip, bcmath

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Composer dependencies
        run: composer install --optimize-autoloader --no-dev

      - name: Install npm dependencies
        run: pnpm install

      - name: Generate key (temporary for build)
        run: php artisan key:generate

      - name: Build assets
        run: pnpm run build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ${{ secrets.VPS_PATH }}
            git pull origin main
            composer install --optimize-autoloader --no-dev
            pnpm install
            pnpm run build

            # Configurar .env se não existir
            if [ ! -f .env ]; then
              cp .env.example .env
              php artisan key:generate
            fi

            # Atualizar configurações .env
            sed -i "s/DB_CONNECTION=.*/DB_CONNECTION=mysql/" .env
            sed -i "s/DB_HOST=.*/DB_HOST=127.0.0.1/" .env
            sed -i "s/DB_PORT=.*/DB_PORT=3306/" .env
            sed -i "s/DB_DATABASE=.*/DB_DATABASE=${{ secrets.DB_DATABASE }}/" .env
            sed -i "s/DB_USERNAME=.*/DB_USERNAME=${{ secrets.DB_USERNAME }}/" .env
            sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/" .env
            sed -i "s/APP_ENV=.*/APP_ENV=production/" .env
            sed -i "s/APP_DEBUG=.*/APP_DEBUG=false/" .env
            sed -i "s|APP_URL=.*|APP_URL=https://belasfindit.emanuelcandido.dev|" .env

            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            sudo chown -R www-data:www-data ${{ secrets.VPS_PATH }}
            sudo chmod -R 755 ${{ secrets.VPS_PATH }}
            sudo chmod -R 775 ${{ secrets.VPS_PATH }}/storage
            sudo chmod -R 775 ${{ secrets.VPS_PATH }}/bootstrap/cache
